// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWPMKfqtjWcdcXOtsSj87MtZywmiET11A',
    appId: '1:472727758354:android:decfbf88d1ed3be13c1acb',
    messagingSenderId: '472727758354',
    projectId: 'madameestservie-90acd',
    databaseURL: 'https://madameestservie-90acd-default-rtdb.firebaseio.com',
    storageBucket: 'madameestservie-90acd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiTAEzmpG2dowlMDhkOavr_QaYe5ksscU',
    appId: '1:472727758354:ios:e8383c2005c229753c1acb',
    messagingSenderId: '472727758354',
    projectId: 'madameestservie-90acd',
    databaseURL: 'https://madameestservie-90acd-default-rtdb.firebaseio.com',
    storageBucket: 'madameestservie-90acd.firebasestorage.app',
    iosClientId: '472727758354-3efd52jdshnhrf16pvbh80uj2l0949gd.apps.googleusercontent.com',
    iosBundleId: 'com.madameestservie.pro',
  );

}